server:
  port: ${PORT:8080}

spring:
  application:
    name: r2dbc-todo-list-app
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/todolist
    username: admin
    password: password
  liquibase:
    change-log: classpath:db/db.changeLog.yaml
    url: jdbc:postgresql://127.0.0.1:5432/todolist
    user: admin
    password: password

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: debug
